const COMMANDS = [
  { text:"When crossing a street, steps follow only one selected color.", time:"aligning", context:"Alignment Pressure", action:"Move", video:"swipetounlock_1.mp4" },
  { text:"Before the signal changes, the body leans forward in anticipation of movement.", time:"waiting", context:"Queue", action:"Move", video:"swipetounlock_1.mp4" },
  { text:"When a surveillance camera is present, movement shifts to avoid its gaze.", time:"suppressing", context:"Under Surveillance", action:"Move", video:"swipetounlock_1.mp4" },
  { text:"Following on-screen instructions, a finger swipes upward to unlock.", time:"executing", context:"Input Required", action:"Operate", video:"swipetounlock_1.mp4" },
  { text:"The face aligns precisely within the frame indicated on screen.", time:"aligning", context:"Validation", action:"Align", video:"swipetounlock_1.mp4" },
  { text:"A progress bar is watched as it fills toward completion.", time:"waiting", context:"Controlled State", action:"Watch", video:"swipetounlock_1.mp4" },
  { text:"Movement aligns in a single direction within a flow.", time:"aligning", context:"Flow", action:"Move", video:"swipetounlock_1.mp4" },
  { text:"In quiet spaces, sound is held back.", time:"suppressing", context:"Suppression State", action:"Suppress", video:"swipetounlock_1.mp4" },
  { text:"Within given options, a single answer is selected.", time:"executing", context:"Validation", action:"Select", video:"swipetounlock_1.mp4" },
  { text:"Personal items are placed in a designated area.", time:"executing", context:"Controlled State", action:"Operate", video:"swipetounlock_1.mp4" },
  { text:"The screen is tapped multiple times when there is no response.", time:"drifting", context:"Input Required", action:"Repeat", video:"swipetounlock_1.mp4" },
  { text:"Specific objects are selected within an image.", time:"executing", context:"Validation", action:"Select", video:"swipetounlock_1.mp4" },
  { text:"Position is adjusted to remain behind a marked line.", time:"suppressing", context:"Controlled State", action:"Hold", video:"swipetounlock_1.mp4" },
  { text:"The same action is repeated after failure.", time:"drifting", context:"Controlled State", action:"Repeat", video:"swipetounlock_1.mp4" },
  { text:"The connection status is monitored through fluctuating signals.", time:"aligning", context:"Flow", action:"Watch", video:"swipetounlock_1.mp4" },
  { text:"An impulse emerges to overturn everything at once.", time:"suppressing", context:"Suppression State", action:"Suppress", video:"swipetounlock_1.mp4" },
  { text:"A fictional exit button is drawn on the wall.", time:"executing", context:"Restricted State", action:"Operate", video:"swipetounlock_1.mp4" },
  { text:"The door is operated without reading the instruction.", time:"executing", context:"Input Required", action:"Operate", video:"swipetounlock_1.mp4" },
  { text:"The elevator button is pressed repeatedly before it responds.", time:"drifting", context:"Controlled State", action:"Repeat", video:"swipetounlock_1.mp4" },
  { text:"On a bright day, one steps outside without wearing sunglasses despite the glare.", time:"executing", context:"Queue", action:"Hold", video:"swipetounlock_1.mp4" },
  { text:"A password is entered to gain access.", time:"executing", context:"Input Required", action:"Enter", video:"swipetounlock_1.mp4" },
  { text:"The process continues until authentication is complete.", time:"drifting", context:"Validation", action:"Repeat", video:"swipetounlock_1.mp4" },
  { text:"When access is denied, attempts are repeated.", time:"drifting", context:"Restricted State", action:"Repeat", video:"swipetounlock_1.mp4" },
  { text:"Access is granted once conditions are met.", time:"executing", context:"Controlled State", action:"Suppress", video:"swipetounlock_1.mp4" },
  { text:"Selection is repeated to verify human identity.", time:"drifting", context:"Validation", action:"Select", video:"swipetounlock_1.mp4" },
  { text:"System entry proceeds by accepting cookies.", time:"executing", context:"Permission State", action:"Select", video:"swipetounlock_1.mp4" },
  { text:"Movement is paused and held in place.", time:"suppressing", context:"Controlled State", action:"Hold", video:"swipetounlock_1.mp4" },
  { text:"Actions proceed by following instructions.", time:"executing", context:"Controlled State", action:"Move", video:"swipetounlock_1.mp4" },
  { text:"The body stabilizes by maintaining internal tension.", time:"aligning", context:"Alignment Pressure", action:"Hold", video:"swipetounlock_1.mp4" },
  { text:"On a rainy day, one walks on without using an umbrella despite getting wet.", time:"executing", context:"Controlled State", action:"Suppress", video:"swipetounlock_1.mp4" }
];