const COMMANDS = [
  {
    id: 1,
    text: "When crossing a street, steps follow only one selected color.",
    korean: "횡단보도를 건널 때, 특정한 색만 골라 밟으며 걷는다.",
    time: "aligning",
    translatedAction: "",
    context: "Alignment Pressure",
    bodyEngagement: "Full Body",
    action: "Move",
    awareness: "Low",
    video: "swipetounlock_1.mp4"
  },
  {
    id: 2,
    text: "Before the signal changes, the body leans forward in anticipation of movement.",
    korean: "신호가 바뀌기 전, 몸이 먼저 앞으로 기울며 출발을 준비한다.",
    time: "waiting",
    translatedAction: "",
    context: "Queue",
    bodyEngagement: "Full Body",
    action: "Move",
    awareness: "Low",
    video: "swipetounlock_1.mp4"
  },
  {
    id: 3,
    text: "When a surveillance camera is present, movement shifts to avoid its gaze.",
    korean: "감시카메라가 보이면, 시선을 피해 이동 경로를 조정한다.",
    time: "suppressing",
    translatedAction: "",
    context: "Under Surveillance",
    bodyEngagement: "Full Body",
    action: "Move",
    awareness: "Medium",
    video: "swipetounlock_1.mp4"
  },
  {
    id: 4,
    text: "Following on-screen instructions, a finger swipes upward to unlock.",
    korean: "화면의 지시에 따라, 손가락을 위로 밀어 잠금을 해제한다.",
    time: "executing",
    translatedAction: "과하게 아래에서 위로 쓸어올린다.",
    context: "Input Required",
    bodyEngagement: "Hand",
    action: "Operate",
    awareness: "Low",
    video: "swipetounlock_1.mp4"
  },
  {
    id: 5,
    text: "The face aligns precisely within the frame indicated on screen.",
    korean: "얼굴은 화면의 가이드에 맞춰 정확한 위치로 정렬된다.",
    time: "aligning",
    translatedAction: "작게 시작해 점점 크게 원을 만들며 회전한다.",
    context: "Validation",
    bodyEngagement: "Face",
    action: "Align",
    awareness: "Low",
    video: "swipetounlock_1.mp4"
  },
  {
    id: 6,
    text: "A progress bar is watched as it fills toward completion.",
    korean: "저장이 완료될 때까지 진행률이 올라가는 화면을 바라본다.",
    time: "waiting",
    translatedAction: "",
    context: "Controlled State",
    bodyEngagement: "Eyes",
    action: "Watch",
    awareness: "Medium",
    video: "swipetounlock_1.mp4"
  },
  {
    id: 7,
    text: "Movement aligns in a single direction within a flow.",
    korean: "보행 흐름에 맞춰 한 방향으로 자연스럽게 정렬된다.",
    time: "aligning",
    translatedAction: "",
    context: "Flow",
    bodyEngagement: "Full Body",
    action: "Move",
    awareness: "Low",
    video: "swipetounlock_1.mp4"
  },
  {
    id: 8,
    text: "In quiet spaces, sound is held back.",
    korean: "조용해야 하는 공간에서 소리를 억제한 채 머문다.",
    time: "suppressing",
    translatedAction: "",
    context: "Suppression State",
    bodyEngagement: "Voice",
    action: "Suppress",
    awareness: "High",
    video: "swipetounlock_1.mp4"
  },
  {
    id: 9,
    text: "Within given options, a single answer is selected.",
    korean: "제시된 보기 안에서 하나의 답을 골라 표시한다.",
    time: "executing",
    translatedAction: "",
    context: "Validation",
    bodyEngagement: "Hand",
    action: "Select",
    awareness: "Medium",
    video: "swipetounlock_1.mp4"
  },
  {
    id: 10,
    text: "Personal items are placed in a designated area.",
    korean: "검사를 위해 소지품을 정해진 위치에 올려놓는다.",
    time: "executing",
    translatedAction: "트레이에 놓는 행위가 점점 과도해진다.",
    context: "Controlled State",
    bodyEngagement: "Hand",
    action: "Operate",
    awareness: "Low",
    video: "swipetounlock_1.mp4"
  },
  {
    id: 11,
    text: "The screen is tapped multiple times when there is no response.",
    korean: "반응이 없을 때 화면을 여러 번 두드린다.",
    time: "drifting",
    translatedAction: "",
    context: "Input Required",
    bodyEngagement: "Hand",
    action: "Repeat",
    awareness: "Low",
    video: "swipetounlock_1.mp4"
  },
  {
    id: 12,
    text: "Specific objects are selected within an image.",
    korean: "이미지 안에서 특정 대상을 골라 선택한다.",
    time: "executing",
    translatedAction: "선택이 점점 불안정해지고 엇나간다.",
    context: "Validation",
    bodyEngagement: "Hand",
    action: "Select",
    awareness: "Low",
    video: "swipetounlock_1.mp4"
  },
  {
    id: 13,
    text: "Position is adjusted to remain behind a marked line.",
    korean: "바닥에 표시된 선을 기준으로 그 뒤에 위치를 맞춘다.",
    time: "suppressing",
    translatedAction: "선을 넘지 않기 위해 몸이 과도하게 조정된다.",
    context: "Controlled State",
    bodyEngagement: "Full Body",
    action: "Hold",
    awareness: "Low",
    video: "swipetounlock_1.mp4"
  },
  {
    id: 14,
    text: "The same action is repeated after failure.",
    korean: "같은 행동을 반복하며 다시 시도한다.",
    time: "drifting",
    translatedAction: "",
    context: "Controlled State",
    bodyEngagement: "Hand",
    action: "Repeat",
    awareness: "Medium",
    video: "swipetounlock_1.mp4"
  },
  {
    id: 15,
    text: "The connection status is monitored through fluctuating signals.",
    korean: "화면의 신호에 따라 데이터 연결 상태를 확인한다.",
    time: "aligning",
    translatedAction: "",
    context: "Flow",
    bodyEngagement: "Eyes",
    action: "Watch",
    awareness: "Low",
    video: "swipetounlock_1.mp4"
  },
  {
    id: 16,
    text: "An impulse emerges to overturn everything at once.",
    korean: "순간적으로 모든 것을 뒤엎고 싶은 충동이 생긴다.",
    time: "suppressing",
    translatedAction: "",
    context: "Suppression State",
    bodyEngagement: "Full Body",
    action: "Suppress",
    awareness: "High",
    video: "swipetounlock_1.mp4"
  },
  {
    id: 17,
    text: "A fictional exit button is drawn on the wall.",
    korean: "존재하지 않는 탈출 버튼을 벽에 그려 넣는다.",
    time: "executing",
    translatedAction: "",
    context: "Restricted State",
    bodyEngagement: "Hand",
    action: "Operate",
    awareness: "High",
    video: "swipetounlock_1.mp4"
  },
  {
    id: 18,
    text: "The door is operated without reading the instruction.",
    korean: "지시를 읽지 않은 채 문을 조작한다.",
    time: "executing",
    translatedAction: "",
    context: "Input Required",
    bodyEngagement: "Hand",
    action: "Operate",
    awareness: "Low",
    video: "swipetounlock_1.mp4"
  },
  {
    id: 19,
    text: "The elevator button is pressed repeatedly before it responds.",
    korean: "엘리베이터 버튼을 반응하기 전에 여러 번 누른다.",
    time: "drifting",
    translatedAction: "",
    context: "Controlled State",
    bodyEngagement: "Hand",
    action: "Repeat",
    awareness: "Low",
    video: "swipetounlock_1.mp4"
  },
  {
    id: 20,
    text: "On a bright day, one steps outside without wearing sunglasses despite the glare.",
    korean: "화창한 날, 눈부심에도 불구하고 선글라스를 쓰지 않은 채 밖으로 나간다.",
    time: "executing",
    translatedAction: "",
    context: "Queue",
    bodyEngagement: "Head",
    action: "Hold",
    awareness: "Medium",
    video: "swipetounlock_1.mp4"
  },
  {
    id: 21,
    text: "A password is entered to gain access.",
    korean: "접근을 위해 비밀번호를 입력한다.",
    time: "executing",
    translatedAction: "",
    context: "Input Required",
    bodyEngagement: "Hand",
    action: "Enter",
    awareness: "Medium",
    video: "swipetounlock_1.mp4"
  },
  {
    id: 22,
    text: "The process continues until authentication is complete.",
    korean: "인증이 완료될 때까지 과정을 반복한다.",
    time: "drifting",
    translatedAction: "",
    context: "Validation",
    bodyEngagement: "Hand",
    action: "Repeat",
    awareness: "Medium",
    video: "swipetounlock_1.mp4"
  },
  {
    id: 23,
    text: "When access is denied, attempts are repeated.",
    korean: "접근이 거부되면 다시 시도를 반복한다.",
    time: "drifting",
    translatedAction: "",
    context: "Restricted State",
    bodyEngagement: "Hand",
    action: "Repeat",
    awareness: "Medium",
    video: "swipetounlock_1.mp4"
  },
  {
    id: 24,
    text: "Access is granted once conditions are met.",
    korean: "조건이 충족되면 접근이 허용된다.",
    time: "executing",
    translatedAction: "",
    context: "Controlled State",
    bodyEngagement: "Hand",
    action: "Suppress",
    awareness: "Low",
    video: "swipetounlock_1.mp4"
  },
  {
    id: 25,
    text: "Selection is repeated to verify human identity.",
    korean: "로봇이 아님을 증명하기 위해 선택 과정을 반복한다.",
    time: "drifting",
    translatedAction: "",
    context: "Validation",
    bodyEngagement: "Hand",
    action: "Select",
    awareness: "Low",
    video: "swipetounlock_1.mp4"
  },
  {
    id: 26,
    text: "System entry proceeds by accepting cookies.",
    korean: "시스템에 진입하기 위해 쿠키 사용에 동의한다.",
    time: "executing",
    translatedAction: "",
    context: "Permission State",
    bodyEngagement: "Hand",
    action: "Select",
    awareness: "Low",
    video: "swipetounlock_1.mp4"
  },
  {
    id: 27,
    text: "Movement is paused and held in place.",
    korean: "움직임을 멈추고 현재 상태를 유지한다.",
    time: "suppressing",
    translatedAction: "",
    context: "Controlled State",
    bodyEngagement: "Full Body",
    action: "Hold",
    awareness: "Low",
    video: "swipetounlock_1.mp4"
  },
  {
    id: 28,
    text: "Actions proceed by following instructions.",
    korean: "지시에 따라 행동하며 다음 단계로 이동한다.",
    time: "executing",
    translatedAction: "",
    context: "Controlled State",
    bodyEngagement: "Full Body",
    action: "Move",
    awareness: "Low",
    video: "swipetounlock_1.mp4"
  },
  {
    id: 29,
    text: "The body stabilizes by maintaining internal tension.",
    korean: "신체의 긴장을 유지하며 균형을 조정한다.",
    time: "aligning",
    translatedAction: "",
    context: "Alignment Pressure",
    bodyEngagement: "Full Body",
    action: "Hold",
    awareness: "Medium",
    video: "swipetounlock_1.mp4"
  },
  {
    id: 30,
    text: "On a rainy day, one walks on without using an umbrella despite getting wet.",
    korean: "비가 내리는 날, 젖어가는 것을 알면서도 우산을 쓰지 않고 걸어간다.",
    time: "executing",
    translatedAction: "",
    context: "Controlled State",
    bodyEngagement: "Full Body",
    action: "Suppress",
    awareness: "Low",
    video: "swipetounlock_1.mp4"
  }
];